name: GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - run: yarn
    - run: |
        git config --global user.email "tamara.cassiani@onfido.com"
        git config --global user.name "TamaraCassiani"

    - run: yarn deploy
      env:
        PA_TOKEN: ${{ secrets.PA_TOKEN }}
        CI: true
